Repository EveripediaNetwork/ep-ui, pull requests merged in 2022-06, with the labels that each got.

#336 Disable Buttons on undefined wikis.
  src/components/Wiki/WikiPage/WikiActionBar.tsx
Labels: bug

#326 UI/UI Fixes for activity and wiki page
  src/components/Activity/ActivityCard.tsx
  src/components/Wiki/WikiPage/InsightComponents/RelatedWikis.tsx
  src/components/Wiki/WikiPage/InsightComponents/TwitterTimeline.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
  src/components/Wiki/WikiPage/WikiActionBar.tsx
  src/components/Wiki/WikiPage/WikiInsights.tsx
  src/components/Wiki/WikiPage/WikiMainContent.tsx
  src/editor-plugins/cite/styles.css
  src/pages/revision/[id].tsx
  src/pages/static/assets/markdown.css
  src/pages/wiki/[slug]/index.tsx
Labels: enhancement

#356 Flexing Logout on Profile dropdown.
  src/components/Layout/Navbar/Logout.tsx
Labels: bug

#374 [Automated] Merge main into Alpha
  .github/workflows/alpha-sync.yml
Labels: auto-merge

#379 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/InsightComponents/TwitterTimeline.tsx
Labels: auto-merge

#381 [Automated] Merge main into Alpha
  src/components/Profile/Collected.tsx
  src/components/Profile/Collections.tsx
  src/components/Profile/CustomTab.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Profile/UserWikis/UserCreatedWikis.tsx
  src/components/Profile/UserWikis/UserEditedWikis.tsx
  src/components/Wiki/WikiPreviewCard/WikiPreviewCard.tsx
  src/services/wikis/index.ts
  src/services/wikis/queries.ts
Labels: auto-merge

#382 [Automated] Merge main into Alpha
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/Image/EditorMainImageWrapper.tsx
  src/components/Elements/ImageInput/ImageInput.tsx
  src/components/Layout/Editor/Highlights/Highlights.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
  src/config/index.ts
  src/data/UrlData.ts
  src/pages/create-wiki/index.tsx
  src/pages/wiki/[slug]/_middleware.ts
Labels: auto-merge

#384 [Automated] Merge main into Alpha
  src/services/activities/queries.ts
Labels: auto-merge

#378 Strip html on Copy/Paste
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/pages/create-wiki/index.tsx
Labels: bug

#387 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/pages/create-wiki/index.tsx
  src/services/token-stats/utils.ts
Labels: auto-merge

#391 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Layout/Navbar/NavSearch/index.tsx
Labels: auto-merge

#392 [Automated] Merge main into Alpha
  src/components/Landing/NotableDrops.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/pages/create-wiki/index.tsx
Labels: auto-merge
