Repository EveripediaNetwork/ep-ui, pull requests merged in 2022-07, with the labels that each got.

#396 [Automated] Merge main into Alpha
  src/components/Profile/LoadingProfile.tsx
  src/components/Profile/UserDetails.tsx
Labels: auto-merge

#398 [Automated] Merge main into Alpha
  src/utils/create-wiki.ts
Labels: auto-merge

#399 [Automated] Merge main into Alpha
  src/components/Activity/ActivityCard.tsx
  src/components/Landing/NotableDrops.tsx
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Navbar/MobileNav.tsx
  src/pages/activity/index.tsx
  src/pages/create-wiki/index.tsx
  src/types/Wiki.ts
  src/utils/PasteListener.ts
  src/utils/create-wiki.ts
Labels: auto-merge

#405 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#406 [Automated] Merge main into Alpha
  src/components/Profile/UserDetails.tsx
Labels: auto-merge

#407 [Automated] Merge main into Alpha
  src/components/About/AboutHero.tsx
Labels: auto-merge

#409 [Automated] Merge main into Alpha
  src/utils/getDeadline.ts
Labels: auto-merge

#411 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#412 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/Tags.tsx
Labels: auto-merge

#408 Support youtube videos on uploads
  next.config.js
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/ImageInput/ImageInput.tsx
  src/components/Layout/Editor/Highlights/MediaModal/MediaModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/RelatedMedia.tsx
  src/utils/i18n.js
  src/utils/mediaUtils.tsx
Labels: enhancement

#414 [Automated] Merge main into Alpha
  next.config.js
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/ImageInput/ImageInput.tsx
  src/components/Layout/Editor/Highlights/MediaModal/MediaModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/RelatedMedia.tsx
  src/utils/i18n.js
  src/utils/mediaUtils.tsx
Labels: auto-merge

#416 [Automated] Merge main into Alpha
  package.json
  src/components/AuthenticatedRoute/index.tsx
  src/components/Elements/Avatar/Avatar.tsx
  src/components/Layout/Navbar/Logout.tsx
  src/components/Layout/Navbar/MobileNav.tsx
  src/components/Layout/Navbar/NavMenu.tsx
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/components/Layout/Navbar/Navbar.tsx
  src/components/Profile/EmptyState.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Profile/UserInfo.tsx
  src/components/Profile/UserWikis/UserCreatedWikis.tsx
  src/components/Profile/UserWikis/UserEditedWikis.tsx
  src/components/Settings/AdvancedSettings.tsx
  src/components/Settings/ImageUpload.tsx
  src/components/Settings/NotificationSettings.tsx
  src/components/Settings/ProfileSettings.tsx
  src/data/NotificationChannelsData.ts
  src/hooks/useWeb3Token.ts
  src/pages/account/SignTokenMessage.tsx
  src/pages/account/[profile].tsx
  src/pages/account/settings.tsx
  src/services/profile/index.tsx
  src/services/profile/queries.ts
  src/services/profile/utils.ts
  src/store/store.ts
  src/theme/semantic-tokens.ts
  src/types/NotificationChannelDataType.ts
  src/types/ProfileType.ts
  yarn.lock
Labels: auto-merge

#423 [Automated] Merge main into Alpha
  package.json
  src/hooks/useConfetti.ts
  src/pages/create-wiki/index.tsx
  yarn.lock
Labels: auto-merge

#424 [Automated] Merge main into Alpha
  src/components/Profile/UserDetails.tsx
Labels: auto-merge

#425 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#429 [Automated] Merge main into Alpha
  src/components/Elements/Image/Image.tsx
  src/components/Elements/Logo/Logo.tsx
  src/components/Landing/Hero.tsx
  src/components/Landing/NotableDrops.tsx
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Editor/EditorWithRef.tsx
  src/components/Layout/Layout/Layout.tsx
  src/pages/account/settings.tsx
  src/pages/index.tsx
  src/theme/styles.ts
Labels: auto-merge

#430 [Automated] Merge main into Alpha
  src/utils/PasteListener.ts
Labels: auto-merge

#434 [Automated] Merge main into Alpha
  public/images/categories/cryptocurrencies.jpg
  public/images/categories/daos.jpg
  public/images/categories/defi.jpg
  public/images/categories/exchanges.jpg
  public/images/categories/nfts.jpg
  public/images/categories/people.jpg
  src/pages/categories/index.tsx
  src/types/Wiki.ts
  src/utils/getDeadline.ts
Labels: auto-merge

#435 [Automated] Merge main into Alpha
  src/components/Icons/coingecko.tsx
  src/components/Icons/coinmarketcap.tsx
  src/components/Icons/emailIcon.tsx
  src/components/Icons/facebookIcon.tsx
  src/components/Icons/githubIcon.tsx
  src/components/Icons/instagramIcon.tsx
  src/components/Icons/redditIcon.tsx
  src/components/Icons/telegramIcon.tsx
  src/components/Icons/twitterIcon.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/types/Wiki.ts
Labels: auto-merge

#440 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Editor/EditorWithRef.tsx
Labels: auto-merge

#441 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#443 [Automated] Merge main into Alpha
  public/images/categories/Cryptocurrency card.png
  public/images/categories/DAO card.png
  public/images/categories/DEFI card.png
  public/images/categories/Exchanges card.png
  public/images/categories/NFTs card.png
  public/images/categories/People of Crypto card.png
Labels: auto-merge

#444 [Automated] Merge main into Alpha
  src/components/Activity/ActivityCard.tsx
  src/components/Elements/Avatar/Avatar.tsx
  src/components/Elements/Image/Image.tsx
  src/components/Landing/Hero.tsx
  src/components/Layout/Navbar/Logout.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Profile/UserInfo.tsx
  src/components/Profile/UserSocialLinks.tsx
  src/components/Profile/UserWikis/UserCreatedWikis.tsx
  src/components/Profile/UserWikis/UserEditedWikis.tsx
  src/components/SEO/UserProfile.tsx
  src/components/Settings/ProfileSettings.tsx
  src/components/Wiki/History/HistoryCard.tsx
  src/components/Wiki/WikiAccordion/AccordionWidget.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiCommiMessage.tsx
  src/components/Wiki/WikiPreviewCard/WikiPreviewCard.tsx
  src/data/UserSocialLinksData.ts
  src/pages/account/[profile].tsx
  src/pages/activity/index.tsx
  src/pages/search/[query].tsx
  src/pages/wiki/[slug]/history.tsx
  src/services/activities/queries.ts
  src/services/profile/index.tsx
  src/services/profile/queries.ts
  src/services/profile/utils.ts
  src/services/wikis/queries.ts
  src/types/Wiki.ts
  src/types/WikiInsightsDataType.ts
  src/utils/getUsername.ts
  src/utils/getWikiSummary.ts
Labels: auto-merge

#449 [Automated] Merge main into Alpha
  next.config.js
Labels: auto-merge

#452 [Automated] Merge main into Alpha
  src/components/Elements/Logo/Logo.tsx
Labels: auto-merge

#455 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#456 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/WikiInsights.tsx
  src/components/Wiki/WikiPage/WikiMainContent.tsx
  src/pages/static/assets/markdown.css
  src/utils/customTableRender.ts
Labels: auto-merge

#458 [Automated] Merge main into Alpha
  .env.example
  next.config.js
  package.json
  public/images/homepage-bg-dark.png
  public/images/homepage-bg-white.png
  src/components/Elements/Avatar/Avatar.tsx
  src/components/Elements/Image/Image.tsx
  src/components/Landing/CategoriesList.tsx
  src/components/Landing/Hero.tsx
  src/components/Landing/HeroCard.tsx
  src/components/Landing/NotableDrops.tsx
  src/components/Layout/Navbar/DesktopNav.tsx
  src/components/Layout/Navbar/MobileNav.tsx
  src/components/Layout/Navbar/Navbar.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Profile/UserSocialLinks.tsx
  src/components/Profile/UserWikis/UserCreatedWikis.tsx
  src/components/Profile/UserWikis/UserEditedWikis.tsx
  src/components/Wiki/WikiPage/CustomRenderers/CiteMarksRender.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
  src/data/NavItemData.ts
  src/pages/account/[profile].tsx
  src/pages/index.tsx
  src/pages/wiki/[slug]/index.tsx
  src/types/ProfileType.ts
  yarn.lock
Labels: auto-merge

#459 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#463 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#464 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#465 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#466 [Automated] Merge main into Alpha
  src/components/Activity/ActivityCard.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
  src/editor-plugins/wikiLink/frame/index.tsx
  src/editor-plugins/wikiLink/index.ts
  src/editor-plugins/wikiLink/styles.css
  src/utils/create-wiki.ts
Labels: auto-merge

#470 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
Labels: auto-merge

#472 [Automated] Merge main into Alpha
  src/components/Wiki/WikiAccordion/index.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileStatistics.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiCommiMessage.tsx
Labels: auto-merge

#474 [Automated] Merge main into Alpha
  src/utils/create-wiki.ts
Labels: auto-merge

#475 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#476 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
Labels: auto-merge

#477 [Automated] Merge main into Alpha
  src/components/About/BlogCard.tsx
  src/components/Layout/Footer/MenuFooter.tsx
  src/components/Wiki/WikiPage/InsightComponents/CurrencyConverter.tsx
  src/store/slices/wiki.slice.ts
  src/types/Wiki.ts
  src/utils/create-wiki.ts
Labels: auto-merge

#478 [Automated] Merge main into Alpha
  package.json
  src/components/AuthenticatedRoute/index.tsx
  src/components/Elements/Avatar/Avatar.tsx
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Layout/Layout/Layout.tsx
  src/components/Layout/Navbar/Logout.tsx
  src/components/Layout/Navbar/MobileNav.tsx
  src/components/Layout/Navbar/Navbar.tsx
  src/components/Layout/Navbar/ProfileLink.tsx
  src/components/Layout/Navbar/ProfileNavItem.tsx
  src/components/Layout/WalletDrawer/ConnectorDetails.tsx
  src/components/Layout/WalletDrawer/Connectors.tsx
  src/components/Layout/WalletDrawer/WalletDrawer.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Settings/ProfileSettings.tsx
  src/components/Wiki/WikiPage/WikiActionBar.tsx
  src/pages/account/settings.tsx
  src/pages/create-wiki/index.tsx
  src/pages/login/index.tsx
  src/utils/create-wiki.ts
  yarn.lock
Labels: auto-merge

#479 [Automated] Merge main into Alpha
  src/components/Landing/HeroCard.tsx
Labels: auto-merge

#483 [Automated] Merge main into Alpha
  package.json
  yarn.lock
Labels: auto-merge

#471 Dynamic color for icon on Profile Summary
  src/components/Icons/coingecko.tsx
  src/components/Icons/coinmarketcap.tsx
  src/components/Icons/emailIcon.tsx
  src/components/Icons/facebookIcon.tsx
  src/components/Icons/githubIcon.tsx
  src/components/Icons/instagramIcon.tsx
  src/components/Icons/redditIcon.tsx
  src/components/Icons/telegramIcon.tsx
  src/components/Icons/twitterIcon.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/theme/foundations/colors.ts
Labels: bug

#485 [Automated] Merge main into Alpha
  src/components/Icons/coingecko.tsx
  src/components/Icons/coinmarketcap.tsx
  src/components/Icons/emailIcon.tsx
  src/components/Icons/facebookIcon.tsx
  src/components/Icons/githubIcon.tsx
  src/components/Icons/instagramIcon.tsx
  src/components/Icons/redditIcon.tsx
  src/components/Icons/telegramIcon.tsx
  src/components/Icons/twitterIcon.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/theme/foundations/colors.ts
Labels: auto-merge

#481 Mobile hamburger menu fix
  src/components/Layout/Navbar/MobileNav.tsx
  src/components/Layout/Navbar/Navbar.tsx
Labels: bug

#487 [Automated] Merge main into Alpha
  src/components/Layout/Navbar/MobileNav.tsx
  src/components/Layout/Navbar/Navbar.tsx
Labels: auto-merge

#490 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#493 [Automated] Merge main into Alpha
  src/components/Landing/HeroCard.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
Labels: auto-merge

#494 [Automated] Merge main into Alpha
  src/components/Elements/Avatar/Avatar.tsx
Labels: auto-merge

#495 [Automated] Merge main into Alpha
  src/pages/static/assets/global.css
  src/utils/PasteListener.ts
Labels: auto-merge

#496 [Automated] Merge main into Alpha
  src/components/Categories/CategoryCard.tsx
  src/pages/categories/[category].tsx
  src/pages/categories/index.tsx
Labels: auto-merge

#497 [Automated] Merge main into Alpha
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/services/search/queries.ts
Labels: auto-merge

#499 [Automated] Merge main into Alpha
  package.json
  src/components/Elements/Avatar/Avatar.tsx
  src/config/wagmi.ts
  src/pages/_app.tsx
  src/utils/create-wiki.ts
  yarn.lock
Labels: auto-merge

#501 [Automated] Merge main into Alpha
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/Image/EditorMainImageWrapper.tsx
  src/components/Wiki/WikiPage/InsightComponents/WikiDetails.tsx
  src/components/Wiki/WikiPreviewCard/WikiPreviewCard.tsx
  src/data/Constants.ts
  src/pages/categories/[category].tsx
Labels: auto-merge

#503 Adding cateogory title in page title for SEO
  src/pages/wiki/[slug]/index.tsx
Labels: enhancement

#504 [Automated] Merge main into Alpha
  src/pages/wiki/[slug]/index.tsx
Labels: auto-merge

#505 [Automated] Merge main into Alpha
  src/components/Layout/Editor/WikiScoreIndicator.tsx
  src/pages/create-wiki/index.tsx
  src/types/Wiki.ts
  src/utils/calculateWikiScore.ts
  src/utils/create-wiki.ts
Labels: auto-merge

#509 [Automated] Merge main into Alpha
  package.json
  src/components/Icons/emailIconColor.tsx
  src/components/Icons/facebookIconColor.tsx
  src/components/Icons/linkedinIconColor.tsx
  src/components/Icons/redditIconColor.tsx
  src/components/Icons/telegramIconColor.tsx
  src/components/Icons/twitterIconColor.tsx
  src/components/Icons/whatsappIconColor.tsx
  src/components/Wiki/WikiPage/CustomModals/ShareWikiModal.tsx
  src/components/Wiki/WikiPage/WikiActionBar.tsx
  src/theme/foundations/colors.ts
  yarn.lock
Labels: auto-merge

#513 [Automated] Merge main into Alpha
  src/utils/PasteListener.ts
Labels: auto-merge

#516 [Automated] Merge main into Alpha
  src/pages/account/[profile].tsx
Labels: auto-merge

#517 [Automated] Merge main into Alpha
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/Elements/Avatar/Avatar.tsx
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/Image/EditorMainImageWrapper.tsx
  src/components/Elements/Image/Image.tsx
  src/components/Elements/Image/ImageCrop.tsx
  src/components/Elements/ImageInput/ImageInput.tsx
  src/components/Elements/Link/Link.tsx
  src/components/Landing/HeroCard.tsx
  src/components/Landing/NotableDrops.tsx
  src/components/Layout/Editor/Highlights/FlexRow/FlexRow.tsx
  src/components/Layout/Editor/Highlights/FlexRowContainer/FlexRowContainer.tsx
  src/components/Layout/Editor/Highlights/Highlights.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/components/Layout/Editor/Highlights/MediaModal/MediaModal.tsx
  yarn.lock
Labels: auto-merge
