Repository EveripediaNetwork/ep-ui, pull requests merged in 2022-10, with the labels that each got.

#768 [Automated] Merge main into Alpha
  src/data/NavItemData.ts
  src/pages/blog/[digest].tsx
  src/theme/semantic-tokens.ts
Labels: auto-merge

#773 [Automated] Merge main into Alpha
  next.config.js
  package.json
  src/components/Layout/GoogleAnalyticsScripts.tsx
  src/components/Layout/Layout/Layout.tsx
  yarn.lock
Labels: auto-merge

#776 [Automated] Merge main into Alpha
  src/components/Admin/WikiCreatedInsight/InsightTableCreatedWiki.tsx
Labels: auto-merge

#774 Feat/blog enhancements
  public/images/cn.svg
  public/images/kr.svg
  src/components/Blog/BlogMdComponents.tsx
  src/components/Blog/BlogPost.tsx
  src/config/index.ts
  src/pages/blog/[digest].tsx
  src/pages/blog/index.tsx
  src/services/blog/index.ts
  src/services/blog/mirror.ts
  src/services/blog/queries.ts
  src/store/store.ts
  src/types/Blog.ts
  src/utils/blog.utils.ts
Labels: bug, enhancement

#778 [Automated] Merge main into Alpha
  public/images/cn.svg
  public/images/kr.svg
  src/components/Blog/BlogMdComponents.tsx
  src/components/Blog/BlogPost.tsx
  src/config/index.ts
  src/pages/blog/[digest].tsx
  src/pages/blog/index.tsx
  src/services/blog/index.ts
  src/services/blog/mirror.ts
  src/services/blog/queries.ts
  src/store/store.ts
  src/types/Blog.ts
  src/utils/blog.utils.ts
Labels: auto-merge

#779 Fix/avatar imports
  src/components/Blog/BlogPost.tsx
  src/pages/blog/[digest].tsx
Labels: bug

#780 [Automated] Merge main into Alpha
  src/components/Blog/BlogPost.tsx
  src/pages/blog/[digest].tsx
Labels: auto-merge

#782 [Automated] Merge main into Alpha
  src/types/Wiki.ts
Labels: auto-merge

#785 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/SummaryInput.tsx
  src/data/Constants.ts
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#787 [Automated] Merge main into Alpha
  src/types/Wiki.ts
Labels: auto-merge

#789 [Automated] Merge main into Alpha
  src/abi/EditorAbi.ts
  src/config/index.ts
  src/data/Constants.ts
  src/hooks/useWhiteListValidator.tsx
  src/pages/create-wiki/index.tsx
  src/types/Wiki.ts
Labels: auto-merge

#793 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/SummaryInput.tsx
Labels: auto-merge

#794 [Automated] Merge main into Alpha
  src/components/Layout/Navbar/NavSearch/index.tsx
Labels: auto-merge

#798 [Automated] Merge main into Alpha
  src/abi/EditorAbi.ts
  src/config/index.ts
  src/hooks/useWhiteListValidator.tsx
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#800 [Automated] Merge main into Alpha
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/services/search/utils.ts
Labels: auto-merge

#802 [Automated] Merge main into Alpha
  src/abi/EditorAbi.ts
  src/config/index.ts
  src/hooks/useWhiteListValidator.tsx
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#806 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Editor.tsx
  src/utils/create-wiki.ts
Labels: auto-merge

#807 [Automated] Merge main into Alpha
  src/abi/EditorAbi.ts
  src/config/index.ts
  src/hooks/useWhiteListValidator.ts
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#810 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/WikiFlaggingSystem.tsx
  src/components/Wiki/WikiPage/WikiInsights.tsx
  src/components/Wiki/WikiPage/WikiMainContent.tsx
  src/components/Wiki/WikiPage/WikiTableOfContents.tsx
Labels: auto-merge

#812 [Automated] Merge main into Alpha
  src/abi/EditorAbi.ts
  src/config/index.ts
  src/hooks/useWhiteListValidator.ts
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#814 [Automated] Merge main into Alpha
  src/components/Layout/Navbar/Navbar.tsx
  src/utils/i18n.js
Labels: auto-merge

#808 Fix/#792
  public/images/cn.svg
  public/images/kr.svg
  src/components/Blog/BlogMdComponents.tsx
  src/components/Blog/BlogPost.tsx
  src/pages/blog/index.tsx
Labels: bug

#820 [Automated] Merge main into Alpha
  public/images/cn.svg
  public/images/kr.svg
  src/components/Blog/BlogMdComponents.tsx
  src/components/Blog/BlogPost.tsx
  src/pages/blog/index.tsx
Labels: auto-merge

#821 [Automated] Merge main into Alpha
  src/components/Layout/Network/NetworkErrorNotification.tsx
Labels: auto-merge

#822 [Automated] Merge main into Alpha
  public/sitemap.txt
Labels: auto-merge

#823 [Automated] Merge main into Alpha
  public/robots.txt
Labels: auto-merge

#827 [Automated] Merge main into Alpha
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#829 [Automated] Merge main into Alpha
  src/components/Admin/WikiDataGraph.tsx
  src/components/Faq/CreateWikisFAQ.tsx
  src/components/Faq/EditingWikisFAQ.tsx
  src/components/Faq/FaqAccordion.tsx
  src/components/Faq/GettingStartedAccordion.tsx
  src/components/Profile/EmptyState.tsx
  src/components/Profile/UserWikis/UserCreatedWikis.tsx
  src/components/Profile/UserWikis/UserEditedWikis.tsx
  src/pages/admin/index.tsx
  src/pages/static/faq.tsx
  src/utils/i18n.js
Labels: auto-merge

#830 [Automated] Merge main into Alpha
  src/components/Landing/CategoriesList.tsx
  src/components/Layout/Navbar/Navbar.tsx
Labels: auto-merge

#833 [Automated] Merge main into Alpha
  src/components/Search/SearchSkeleton.tsx
Labels: auto-merge

#834 [Automated] Merge main into Alpha
  src/pages/blog/index.tsx
Labels: auto-merge

#835 [Automated] Merge main into Alpha
  src/components/SEO/Activity.tsx
  src/components/SEO/Blog.tsx
  src/components/SEO/SettingPage.tsx
  src/components/SEO/Static.tsx
  src/components/SEO/Wiki.tsx
  src/components/Settings/AdvancedSettings.tsx
  src/pages/account/settings.tsx
  src/pages/activity/index.tsx
  src/pages/blog/[digest].tsx
  src/pages/blog/index.tsx
  src/pages/revision/[id].tsx
  src/pages/search/[query].tsx
  src/pages/static/about.tsx
  src/pages/static/careers.tsx
  src/pages/static/faq.tsx
  src/pages/static/guidelines.tsx
  src/pages/static/privacy.tsx
  src/pages/static/terms.tsx
Labels: auto-merge

#838 [Automated] Merge main into Alpha
  src/components/SEO/Wiki.tsx
Labels: auto-merge

#839 [Automated] Merge main into Alpha
  src/pages/blog/index.tsx
Labels: auto-merge

#840 [Automated] Merge main into Alpha
  src/components/Faq/CreateWikisFAQ.tsx
  src/components/Faq/EditingWikisFAQ.tsx
Labels: auto-merge

#841 [Automated] Merge main into Alpha
  src/components/Layout/WalletDrawer/Connectors.tsx
Labels: auto-merge

#843 [Automated] Merge main into Alpha
  src/components/Layout/WalletDrawer/Connectors.tsx
Labels: auto-merge

#845 [Automated] Merge main into Alpha
  src/components/Settings/NotificationInfo.tsx
  src/components/Settings/NotificationSettings.tsx
  src/components/Settings/ProfileSettings.tsx
  src/data/NavItemData.ts
  src/data/NotificationChannelsData.ts
Labels: auto-merge

#846 [Automated] Merge main into Alpha
  src/utils/i18n.js
Labels: auto-merge

#847 [Automated] Merge main into Alpha
  src/components/Layout/Footer/MenuFooter.tsx
Labels: auto-merge

#850 [Automated] Merge main into Alpha
  src/pages/static/guidelines.tsx
  src/pages/static/privacy.tsx
Labels: auto-merge

#851 [Automated] Merge main into Alpha
  public/images/AboutSecHeroDark.png
  public/images/AboutSecHeroLight.png
  public/images/about-hero-dark.svg
  public/images/about-hero-light.svg
  public/images/team/andy.png
  public/images/team/justin-moore.png
  public/images/team/justin.png
  public/images/team/kesar.png
  public/images/team/kevin.png
  public/images/team/navin.png
  public/images/team/richard.png
  public/images/team/robertto.png
  public/images/team/sam.png
  public/images/team/suchet.png
  public/images/team/theodor.png
  public/images/team/travis.png
  public/images/team/violetta.png
  src/components/About/AboutCommunity.tsx
  src/components/About/AboutFeatures.tsx
  src/components/About/AboutHero.tsx
  src/components/About/AboutOurTeam.tsx
  src/components/About/AboutTestimonial.tsx
  src/components/About/logos/everipedia.svg
  src/components/About/logos/iq-grey.svg
  src/components/About/logos/iq.svg
  src/data/MeetOurTeamData.ts
  src/pages/static/about.tsx
  src/types/TeamDataType.ts
  src/utils/i18n.js
Labels: auto-merge

#854 [Automated] Merge main into Alpha
  src/components/Layout/Footer/Footer.tsx
Labels: auto-merge

#855 [Automated] Merge main into Alpha
  public/images/og-image-default.png
  src/components/SEO/Activity.tsx
  src/components/SEO/Blog.tsx
  src/components/SEO/Default.tsx
  src/components/SEO/SettingPage.tsx
  src/components/SEO/Static.tsx
Labels: auto-merge

#856 [Automated] Merge main into Alpha
  src/utils/i18n.js
Labels: auto-merge

#857 [Automated] Merge main into Alpha
  src/data/SocialsData.ts
Labels: auto-merge

#859 [Automated] Merge main into Alpha
  public/images/team/ted.png
  public/images/team/theodor.png
  src/data/MeetOurTeamData.ts
Labels: auto-merge

#862 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/InsightComponents/CurrencyConverter.tsx
Labels: auto-merge

#869 [Automated] Merge main into Alpha
  src/pages/api/revalidate.ts
Labels: auto-merge

#870 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/CustomRenderers/LinkRenderers/WikiLinkRender.tsx
Labels: auto-merge

#872 [Automated] Merge main into Alpha
  src/components/Layout/Footer/Footer.tsx
  src/components/Layout/Navbar/NavSearch/index.tsx
  src/components/Layout/Navbar/WalletNavMenu.tsx
  src/components/Layout/WalletDrawer/ConnectorDetails.tsx
  src/components/Layout/WalletDrawer/Connectors.tsx
  src/components/Settings/NotificationSettings.tsx
  src/pages/create-wiki/index.tsx
  src/services/search/utils.ts
  src/types/global.d.ts
  src/utils/create-wiki.ts
  src/utils/googleAnalytics.ts
Labels: auto-merge

#874 [Automated] Merge main into Alpha
  src/components/Settings/ProfileSettings.tsx
  src/pages/account/settings.tsx
Labels: auto-merge

#877 [Automated] Merge main into Alpha
  src/services/token-stats/utils.ts
Labels: auto-merge

#878 [Automated] Merge main into Alpha
  package.json
  src/config/wagmi.ts
  yarn.lock
Labels: auto-merge

#880 [Automated] Merge main into Alpha
  src/components/Activity/ActivityCard.tsx
Labels: auto-merge

#882 [Automated] Merge main into Alpha
  src/utils/googleAnalytics.ts
Labels: auto-merge

#883 [Automated] Merge main into Alpha
  src/components/Layout/WalletDrawer/Connectors.tsx
Labels: auto-merge

#884 [Automated] Merge main into Alpha
  src/components/Elements/LinkElements/LinkOverlay.tsx
  src/components/Elements/LinkElements/PatchedLinkOverlay.tsx
  src/components/Profile/UserSocialLinks.tsx
  src/components/Wiki/History/HistoryCard.tsx
  src/components/Wiki/WikiPage/InsightComponents/ProfileSummary.tsx
  src/components/Wiki/WikiPage/WikiReferences.tsx
Labels: auto-merge

#887 [Automated] Merge main into Alpha
  src/data/WikiLinks.ts
Labels: auto-merge

#888 [Automated] Merge main into Alpha
  package.json
  src/components/Elements/EditorRank/EditorRank.tsx
  src/components/Landing/Leaderboard.tsx
  src/components/Profile/CustomTab.tsx
  src/components/Profile/UserDetails.tsx
  src/config/index.ts
  src/pages/index.tsx
  src/services/editor/index.ts
  src/services/editor/queries.ts
  src/store/slices/index.ts
  src/store/slices/leaderboard.ts
  src/store/store.ts
  src/theme/semantic-tokens.ts
  src/utils/leaderboard.utils.ts
  yarn.lock
Labels: auto-merge

#889 [Automated] Merge main into Alpha
  README.md
Labels: auto-merge

#892 [Automated] Merge main into Alpha
  src/components/Wiki/WikiAccordion/AccordionWidget.tsx
  src/components/Wiki/WikiPage/InsightComponents/NFTStatistics.tsx
  src/components/Wiki/WikiPage/WikiInsights.tsx
  src/data/WikiLinks.ts
  src/services/nft-stats/index.ts
  src/services/nft-stats/utils.ts
  src/store/store.ts
  src/types/WikiInsightsDataType.ts
Labels: auto-merge

#894 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/data/WikiLinks.ts
Labels: auto-merge

#895 [Automated] Merge main into Alpha
  src/services/token-stats/index.ts
  src/services/token-stats/queries.ts
  src/services/token-stats/utils.ts
Labels: auto-merge

#896 [Automated] Merge main into Alpha
  src/components/Admin/WikiEditorInsight/WikiEditorsInsight.tsx
  src/components/Wiki/WikiPage/InsightComponents/NFTWidget.tsx
  src/components/Wiki/WikiPage/WikiInsights.tsx
  src/services/nftlisting/index.ts
  src/store/store.ts
Labels: auto-merge

#898 [Automated] Merge main into Alpha
  src/components/Landing/Leaderboard.tsx
Labels: auto-merge

#901 [Automated] Merge main into Alpha
  src/components/Layout/GoogleAnalyticsScripts.tsx
  src/components/Layout/WalletDrawer/Connectors.tsx
  src/components/Wagmi/DynamicWagmiProvider.tsx
Labels: auto-merge

#904 [Automated] Merge main into Alpha
  src/pages/index.tsx
Labels: auto-merge

#907 [Automated] Merge main into Alpha
  src/pages/index.tsx
Labels: auto-merge

#908 [Automated] Merge main into Alpha
  public/brokenImg.png
  src/components/Wiki/WikiPage/InsightComponents/NFTImageFallBack.tsx
  src/components/Wiki/WikiPage/InsightComponents/NFTWidget.tsx
  src/services/nftlisting/index.ts
Labels: auto-merge

#910 [Automated] Merge main into Alpha
  src/data/NavItemData.ts
Labels: auto-merge

#911 [Automated] Merge main into Alpha
  src/components/Layout/Footer/MenuFooter.tsx
  src/components/SEO/Activity.tsx
  src/components/SEO/CreateWikiPage.tsx
  src/components/SEO/SettingPage.tsx
  src/components/SEO/UserProfile.tsx
  src/components/SEO/Wiki.tsx
  src/pages/account/[profile].tsx
  src/pages/account/settings.tsx
  src/pages/categories/[category].tsx
  src/pages/categories/index.tsx
  src/pages/create-wiki/index.tsx
Labels: auto-merge

#913 [Automated] Merge main into Alpha
  src/pages/activity/index.tsx
  src/pages/create-wiki/index.tsx
  src/pages/tags/[tag].tsx
Labels: auto-merge

#916 [Automated] Merge main into Alpha
  public/images/categories/dapps-card.jpg
  public/images/categories/dapps.jpg
  src/data/AllCategoriesData.ts
  src/data/NavItemData.ts
Labels: auto-merge

#918 [Automated] Merge main into Alpha
  src/editor-plugins/cite/frame/ReferenceCard.tsx
Labels: auto-merge

#922 [Automated] Merge main into Alpha
  src/components/Wiki/WikiPage/InsightComponents/RelatedWikis.tsx
  src/pages/wiki/[slug]/index.tsx
Labels: auto-merge

#923 [Automated] Merge main into Alpha
  src/components/Admin/WikiCreatedInsight/InsightTableCreatedWiki.tsx
  src/components/Admin/WikiCreatedInsight/PromoteCreatedWikisModal.tsx
  src/components/Admin/WikiCreatedInsight/WikiInsightTable.tsx
  src/components/Admin/WikiDataGraph.tsx
  src/components/Admin/WikiDetailsCards.tsx
  src/components/Admin/WikiEditorInsight/InsightTableWikiEditors.tsx
  src/components/Admin/WikiEditorInsight/WikiEditorsInsight.tsx
  src/components/Elements/Image/Image.tsx
  src/components/Elements/LinkElements/PatchedLinkOverlay.tsx
  src/components/Layout/WalletDrawer/Connectors.tsx
  src/components/Profile/UserDetails.tsx
  src/components/Wiki/WikiPage/InsightComponents/NFTWidget.tsx
  src/hooks/useConfetti.ts
  src/pages/admin/index.tsx
  src/pages/create-wiki/index.tsx
  src/pages/login/index.tsx
  src/services/search/utils.ts
  src/utils/blog.utils.ts
Labels: auto-merge

#925 [Automated] Merge main into Alpha
  src/components/Layout/Editor/Highlights/Highlights.tsx
  src/utils/create-wiki.ts
Labels: auto-merge
