Repository EveripediaNetwork/ep-ui, pull requests merged in 2022-03, with the labels that each got.

#45 "Create wiki" updates
  package.json
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Editor/Highlights/Highlights.tsx
  src/components/Layout/Editor/Highlights/HighlightsModal/HighlightsModal.tsx
  src/constant/pageTemplate.ts
  src/pages/_app.tsx
  src/pages/api/dev/index.ts
  src/pages/create-wiki/index.tsx
  src/pages/static/assets/global.css
  src/store/slices/wiki.slice.ts
  src/types/CategoryDataTypes.ts
  src/types/Wiki.ts
  src/utils/getWikiFields.ts
Labels: bug, enhancement

#72 Fixes issues#157- User address is shorted when creating the IPFS in create wiki
  src/pages/create-wiki/index.tsx
Labels: bug

#76 Updating Browserstorage to remove expiry bug.
  src/utils/browserStorage.ts
Labels: bug

#94 Feat/edit page
  src/components/Elements/Dropzone/Dropzone.tsx
  src/components/Elements/ImageInput/ImageInput.tsx
  src/components/Layout/Editor/Editor.tsx
  src/components/Layout/Editor/Highlights/Highlights.tsx
  src/context/image.context.tsx
  src/pages/_app.tsx
  src/pages/create-wiki/index.tsx
  src/store/slices/wiki.slice.ts
  src/types/Wiki.ts
  src/utils/postSignature.ts
Labels: enhancement

#99 fix: edit page bugs
  src/pages/create-wiki/index.tsx
Labels: bug
